### ISSUE TITLE
Still up for MH?

### ISSUE THREAD

**Issue by nobodyrandom** [devcnn88/hello-world#3]
Hey CnN,

Got plans to patch for MH Jan 10 update? Changes are mostly on GUI

I don't have time to patch my ver of the bot and I don't think there are any other vers of the bot available at the moment.

**Comment by devcnn88** [comment]
I'm outstation right now and have limited access to internet. Unfortunately you have to patch it yourself at this moment.

**Comment by nobodyrandom** [comment]
👍
